### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by Bruno-366** [willnorris/webmention#11]
Any chance you could add a man page, and link to it from the README? Right now documentation is a bit sparse, although looking at the code, it seems simple enough to use.

**Comment by nekr0z** [comment]
I'd argue the [existing GoDoc](https://pkg.go.dev/willnorris.com/go/webmention@v0.0.0-20210415160817-80522679a91f/cmd/webmention) that can be found from the README link gives enough information together with the `--help` option that explains the flags (or, rather, the flag, since the command line tool only has one).

However, I can see how someone might want
- a direct link to that GoDoc from the README;
- a couple more lines of explanation in it.

**Comment by Bruno-366** [comment]
very well
