### ISSUE TITLE
This library is copyright Google

### ISSUE THREAD

**Issue by ghost** [willnorris/webmention#9]
Why?

**Comment by jhabdas** [comment]
Thanks for the info @willnorris. I remember now those terms of the Google contract. They really got ahead of the law there, though I believe the same to be true of any open source work performed while under similar employment contracts—I'm just not aware of any precedent set yet (maybe you know?)

Anyway, thanks for creating this library. If you're able to dual license this in the future and release the copyright to GPL or WTFPL please do comment here so I may pursue using this library.

Cheers.

**Comment by jhabdas** [comment]
Thanks for the info @willnorris. I remember now those terms of the Google contract. They really got ahead of the law there, though I believe the same to be true of any open source work performed while under similar employment contracts—I'm just not aware of any precedent set yet (maybe you know?)

Anyway, thanks for creating this library. If you happen to know of a similar work written in Go and not copywritten by Google I'd love to get my hands on it.

Cheers.

**Comment by willnorris** [comment]
I'm just curious, why does the Google copyright matter?  It's still under an open source license, so your rights as a user of the library are exactly the same.

(Not saying you don't have your reasons, I'm just curious what they are.)

**Comment by jhabdas** [comment]
I disagree with the GNU's definition of _free_ software. To me _free_ software is simply one which is free of burden, thereby maximizing its potential for reuse. Burden, in this sense, means software which is difficult to use because of onerous licensing requirements (like the GNU) or limitations of warranty and liability. But that's just my turn off with the BSD. Google is a [different matter entirely](https://www.publicaffairsbooks.com/titles/shoshana-zuboff/the-age-of-surveillance-capitalism/9781610395694/).

**Comment by jhabdas** [comment]
I disagree with the GNU's definition of _free_ software. To me _free_ software is simply one which is free of burden, thereby maximizing its potential for reuse. Burden, in this sense, means software which is difficult to use because of onerous licensing requirements (like the GNU) or limitations of warranty and liability. But that's just my turn off with the BSD and the like. Google is a [different matter entirely](https://www.theguardian.com/technology/2019/jan/20/shoshana-zuboff-age-of-surveillance-capitalism-google-facebook) and one I've been concerned about since the day Google purchased DoubleClick.
